packages:
  - packages/@types/*
  - packages/*
  - test/

catalog:
  "@biomejs/biome": "^1.9.4"
  "@fastify/cors": ^10.0.0
  "@mikro-orm/cli": ^6.0.0
  "@mikro-orm/core": ^6.0.0
  "@mikro-orm/migrations": ^6.0.0
  "@mikro-orm/mysql": ^6.0.0
  "@mikro-orm/reflection": ^6.0.0
  "@slack/web-api": ^7.0.0
  "@types/express": ^4.17.21
  "@types/node": ^20.17.19
  "@vitest/coverage-istanbul": ^3.0.0
  ajv: ^8.12.0
  ajv-errors: ^3.0.0
  ajv-formats: ^3.0.0
  commander: ^12.0.0
  dotenv: ^16.3.1
  fastify: ^5.0.0
  greenit-cli: git+ssh://git@github.com:cnumr/GreenIT-Analysis-cli.git#9a14a0899c7013d64eeda58eb80afb4b9d3aaef7
  lighthouse: ^12.0.0
  memfs: ^4.11.1
  ora: ^8.0.1
  pino: ^9.0.0
  pino-pretty: ^13.0.0
  rimraf: ^5.0.9
  ts-node: ^10.9.1
  type-fest: ^4.9.0
  typescript: ^5.6.2
  vitest: ^3.0.0

catalogs:
  # align puppeteer-core version with the puppeteer version used by the lighthouse or greenit-cli dependency
  # this allows to:
  # - limit the number of puppeteer* dependencies installed
  # - avoid to install additional Chrome browsers in different versions (as puppeteer embed Chrome, but puppeteer-core doesn't)
  puppeteerLighthouse:
    puppeteer-core: ^23.10.4
  puppeteerGreenIT:
    puppeteer-core: ^23.9.0
