#!/bin/bash

# add updated jsr metadata to the previous commit generated by the "changeset version" CLI.

# current commit message
COMMIT_MESSAGE=$(git log -1 --pretty=%B)
# commit message generated by the "changeset version" CLI
PATTERN=^RELEASING

if ! [[ "$COMMIT_MESSAGE" =~ $PATTERN ]]; then
    ./devops/scripts/update-jsr.sh
    git add packages/**/jsr.jsonc
    git commit --amend --no-edit
fi
