#!/bin/bash

# add updated jsr metadata to the previous commit generated by the "changeset version" CLI.

# current commit message. see https://stackoverflow.com/a/44423052
INPUT_FILE=$1
COMMIT_MESSAGE=$(head -n1 "$INPUT_FILE")
# commit message generated by the "changeset version" CLI
PATTERN=^RELEASING

if [[ "$COMMIT_MESSAGE" =~ $PATTERN ]]; then
    touch ./need-jsr-updated.tmp
fi
