#!/usr/bin/env bash
set -eo pipefail

# Automatically generated by moon. DO NOT MODIFY!
# https://moonrepo.dev/docs/guides/vcs-hooks

moon run :lint :format --affected --status=staged -- --staged --files-ignore-unknown=true --no-errors-on-unmatched

