#!/usr/bin/env bash
set -eo pipefail

# Automatically generated by moon. DO NOT MODIFY!
# https://moonrepo.dev/docs/guides/vcs-hooks

moon run :check --affected --status=staged -- --write --staged --files-ignore-unknown=true --no-errors-on-unmatched

