name: Check code

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    name: 🧹 Lint & format
    runs-on: ubuntu-latest
    timeout-minutes: 8
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Setup Moon toolchain
        uses: moonrepo/setup-toolchain@937d7dbbc1ec218aa8641c792d5821addebd9f03 # v0
        with:
          auto-install: true

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Lint & format
        run: moon ci :check --color
        env:
          # disable browser download on puppeteer install. see https://pptr.dev/api/puppeteer.configuration
          PUPPETEER_SKIP_DOWNLOAD: true
      
      - uses: appthrust/moon-ci-retrospect@10c4aff093e3405433957d8e1d2776c81207d5bb # v1
        if: success() || failure()
