name: Check code

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    name: 🧹 Lint & format
    runs-on: ubuntu-latest
    timeout-minutes: 8
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Setup Moon toolchain
        uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095 # v0
        with:
          auto-install: true

      - name: Lint & format
        run: moon ci :check
        env:
          # disable browser download on puppeteer install. see https://pptr.dev/api/puppeteer.configuration
          PUPPETEER_SKIP_DOWNLOAD: true
