name: Check code

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    name: 🧹 Lint & format
    runs-on: ubuntu-latest
    timeout-minutes: 8
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Setup Moon toolchain
        uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095 # v0
        with:
          auto-install: true

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Lint & format
        run: moon ci :check --color
        env:
          # disable browser download on puppeteer install. see https://pptr.dev/api/puppeteer.configuration
          PUPPETEER_SKIP_DOWNLOAD: true
      
      - uses: appthrust/moon-ci-retrospect@2b2216c99fa8d657ee43bf788b09943fb34c169c # v2
        if: success() || failure()
