name: Tests

on: pull_request

jobs:
  test:
    name: 🐛 Run tests
    runs-on: ubuntu-latest
    outputs:
      # Output the artifact upload id
      artifact-upload-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    timeout-minutes: 8
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        node_version: [20, 22, 24, 25]

    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0

      - name: Set Node.js version
        run: sed -Ei 's/(node = ).*/\1"^${{ matrix.node_version}}"/' .prototools

      - name: Setup Moon toolchain
        uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095 # v0
        with:
          auto-install: true

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        name: Setup pnpm cache
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
            /home/runner/.cache/puppeteer
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Run tests
        run: moon run :test
